const expr = require("express");
const app = expr();
const path = require("path");
css_path = path.join(__dirname, "../CSS");
html_path = path.join(__dirname, "../HTML");
img_path = path.join(__dirname, "../IMAGE");
app.use(expr.static(css_path));
app.use(expr.static(img_path));
app.use(expr.static(html_path));
app.listen(2005);
